### ISSUE TITLE
Looking for a source

### ISSUE THREAD

**Issue by Adephx** [1101839859/EvolveLegacyReborn#1]
Hi. I've been told by the Evolve community, that you are the author behind this version of the RebornEvolve emulator: https://www.filemail.com/d/nkotazjfwxpgpca

Is there any chance that you would be willing to update the GitHub or share the source files, because I would love to add features and update the GUI?

**Comment by PaienNate** [comment]
Sure, I'll upload my newest code. I upload this code when I'm unfamiliar with git.
Hope I can write a good tutorial for how to compile these code, as you see now it doesn't have a tutorial for how to compile and use it.

**Comment by PaienNate** [comment]
> Hi. I've been told by the Evolve community, that you are the author behind this version of the RebornEvolve emulator: https://www.filemail.com/d/nkotazjfwxpgpca
> 
> Is there any chance that you would be willing to update the GitHub or share the source files, because I would love to add features and update the GUI?

I have upload the newest file and try my best to make comment in english. Hope can help you.
